import {readFile,writeFile,mkdir,readdir,cp,rm} from 'node:fs/promises';
const site=JSON.parse(await readFile('content/site.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const files=await readdir('content/posts');
const posts=await Promise.all(files.filter(f=>f.endsWith('.json')).map(async f=>JSON.parse(await readFile('content/posts/'+f,'utf8'))));
posts.sort((a,b)=>b.date.localeCompare(a.date)||a.slug.localeCompare(b.slug));
await rm('docs',{recursive:true,force:true});await mkdir('docs',{recursive:true});await cp('public','docs',{recursive:true});
const arrow='<span aria-hidden="true">↗</span>';
const social=()=>Object.entries(site.socials).map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(n)} ${arrow}</a>`).join('')+(site.email?`<a href="mailto:${esc(site.email)}">Gmail ${arrow}</a>`:'');
function layout(title,description,path,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#ffffff"><link rel="canonical" href="${site.origin}${path}"><meta property="og:type" content="${path.startsWith('/blog/')&&path!='/blog/'?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site.origin}${path}"><meta property="og:image" content="${site.origin}/social.svg"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="Akhila's writing" href="/feed.xml"><link rel="stylesheet" href="/style.css?v=2"></head><body><a class="skip" href="#main">Skip to content</a><div class="shell">${path==='/'?'':`<header><a href="/">← ${esc(site.name)}</a></header>`}<main id="main">${body}</main><footer><span>${esc(site.name)}</span><a href="/feed.xml">RSS</a></footer></div></body></html>`;}
const rows=posts.map(p=>`<li><a href="/blog/${p.slug}/">${esc(p.title)}</a><p>${esc(p.summary)}</p></li>`).join('');
const home=`<section class="intro"><h1>Akhila Datta Dola</h1><p>I’m a data scientist and IIT Madras graduate. I work on multimodal AI, speech, and reasoning.</p><p>Creator of <a href="https://huggingface.co/akhilaaa3/Jev-Omni">Jev-Omni</a>.</p><div class="socials">${social()}</div></section><section><h2>Projects</h2><ul class="entries"><li><a href="https://huggingface.co/akhilaaa3/Jev-Omni">Jev-Omni</a><p>An open model for decisions across text, images, audio, and video. <a href="https://huggingface.co/spaces/akhilaaa3/jev-omni">Try the demo.</a></p></li><li><a href="https://github.com/adola700/vee-ana">Hinglish text-to-speech</a><p>Fine-tuning and streaming inference for Hindi–English speech.</p></li></ul></section><section><h2>Writing</h2><ul class="entries">${rows}</ul></section>`;
await writeFile('docs/index.html',layout(site.name+' — Open models & machine learning','Creator of Jev-Omni. Open models, speech experiments, and notes on applied machine learning.','/',home));
await mkdir('docs/blog',{recursive:true});await writeFile('docs/blog/index.html',layout('Writing — '+site.name,'Project notes on multimodal AI, speech, and machine learning.','/blog/',`<section class="blog-header"><h1>Writing</h1><p>Notes on models and experiments.</p></section><ul class="entries">${rows}</ul>`));
for(const p of posts){const html=`<article class="article"><a class="quiet-link" href="/blog/">← All writing</a><div class="article-meta eyebrow">${esc(p.category)} · ${esc(p.label)} · ${p.readTime} read</div><h1>${esc(p.title)}</h1><p class="article-deck">${esc(p.summary)}</p><div class="byline">${esc(site.name)}<span>Published ${new Date(p.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</span></div><div class="prose">${p.sections.map(s=>(s.heading?`<h2>${esc(s.heading)}</h2>`:'')+`<p>${esc(s.text)}</p>`).join('')}<aside class="source-note"><p>${esc(p.editorialNote)}</p><a href="${esc(p.source)}" target="_blank" rel="noopener noreferrer">${esc(p.sourceLabel)} ${arrow}</a></aside></div></article>`;await mkdir('docs/blog/'+p.slug,{recursive:true});await writeFile('docs/blog/'+p.slug+'/index.html',layout(p.title+' — '+site.name,p.summary,'/blog/'+p.slug+'/',html));}
await writeFile('docs/404.html',layout('Page not found — '+site.name,'This page could not be found.','/404',`<section class="blog-header"><h1>Page not found</h1><p>That page isn’t here.</p><a class="button" href="/">Back home →</a></section>`));
await writeFile('docs/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(site.name)} — Writing</title><link>${site.origin}/blog/</link><description>Project notes and experiments.</description>${posts.map(p=>`<item><title>${esc(p.title)}</title><link>${site.origin}/blog/${p.slug}/</link><guid>${site.origin}/blog/${p.slug}/</guid><pubDate>${new Date(p.date+'T12:00:00Z').toUTCString()}</pubDate><description>${esc(p.summary)}</description></item>`).join('')}</channel></rss>`);
await writeFile('docs/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/blog/',...posts.map(p=>'/blog/'+p.slug+'/')].map(p=>`<url><loc>${site.origin}${p}</loc></url>`).join('')}</urlset>`);
await writeFile('docs/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site.origin}/sitemap.xml\n`);
console.log(`Built home, blog, ${posts.length} articles, RSS, sitemap, and 404.`);
