import {readFile,writeFile,mkdir,readdir,cp,rm} from 'node:fs/promises';
const site=JSON.parse(await readFile('content/site.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const files=await readdir('content/posts');
const posts=await Promise.all(files.filter(f=>f.endsWith('.json')).map(async f=>JSON.parse(await readFile('content/posts/'+f,'utf8'))));
posts.sort((a,b)=>b.date.localeCompare(a.date)||a.slug.localeCompare(b.slug));
await rm('docs',{recursive:true,force:true});await mkdir('docs',{recursive:true});await cp('public','docs',{recursive:true});
const arrow='<span aria-hidden="true">↗</span>';
const social=()=>Object.entries(site.socials).map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(n)} ${arrow}</a>`).join('')+(site.email?`<a href="mailto:${esc(site.email)}">Gmail ${arrow}</a>`:'');
function layout(title,description,path,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f7f6f2"><link rel="canonical" href="${site.origin}${path}"><meta property="og:type" content="${path.startsWith('/blog/')&&path!='/blog/'?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site.origin}${path}"><meta property="og:image" content="${site.origin}/social.svg"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="Akhila's writing" href="/feed.xml"><link rel="stylesheet" href="/style.css"></head><body><a class="skip" href="#main">Skip to content</a><div class="shell"><header><a class="wordmark" href="/" aria-label="Akhila Datta Dola home">ad<span class="dot">.</span></a><nav aria-label="Main navigation"><a href="/#work">Work</a><a href="/blog/" ${path.startsWith('/blog')?'aria-current="page"':''}>Writing</a><a href="/#about">About</a><a href="#contact">Contact <span aria-hidden="true">↗</span></a></nav></header><main id="main">${body}</main><footer id="contact"><div class="footer-top"><div><span class="eyebrow">LET’S CONNECT</span><h2>Good work starts with<br>a conversation.</h2></div><a class="circle-link" href="${site.email?'mailto:'+esc(site.email):site.socials.X}" aria-label="${site.email?'Email me':'Find me on X'}">↗</a></div><div class="socials">${social()}</div><div class="footer-bottom"><span>© ${new Date().getFullYear()} ${esc(site.name)}</span><span>Built with curiosity.</span><a href="/feed.xml">RSS ↗</a></div></footer></div></body></html>`;}
const rows=posts.map(p=>`<a class="post-row" href="/blog/${p.slug}/"><span class="post-category">${esc(p.category)}</span><div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p></div><span class="post-end">${p.readTime}<span aria-hidden="true">↗</span></span></a>`).join('');
const home=`<section class="hero"><div class="eyebrow"><span class="live-dot"></span> OPEN MODELS · APPLIED MACHINE LEARNING</div><h1>Akhila Datta<br><em>Dola.</em></h1><p class="intro">I build models that see, hear, and make decisions.<br>Creator of <a href="https://huggingface.co/akhilaaa3/Jev-Omni">Jev-Omni</a>.</p><div class="hero-bottom"><div class="socials">${social()}</div><a class="quiet-link" href="#work">Explore my work <span aria-hidden="true">↓</span></a></div></section><section id="work" class="section"><div class="section-heading"><h2>Selected work</h2><span class="eyebrow">01 / BUILDING</span></div><article class="featured"><div class="feature-copy"><span class="eyebrow">FEATURED PROJECT</span><h3>Jev-Omni<span class="dot">.</span></h3><p>A multimodal decision model. Give it context and a set of choices; get a probability for each option.</p><div class="tags"><span>Open weights</span><span>Multimodal</span></div><a class="button" href="https://huggingface.co/akhilaaa3/Jev-Omni" target="_blank" rel="noopener noreferrer">Explore the model ${arrow}</a><a class="text-link" href="https://huggingface.co/spaces/akhilaaa3/jev-omni" target="_blank" rel="noopener noreferrer">Try the demo ${arrow}</a></div><div class="model-art" role="img" aria-label="Text, image, audio, and video inputs flow into Jev-Omni to produce a decision"><div class="art-caption">FOUR MODALITIES. ONE DECISION.</div><div class="inputs"><span>T<span>Text</span></span><span>▧<span>Image</span></span><span>≋<span>Audio</span></span><span>▷<span>Video</span></span></div><div class="converge"></div><div class="model-node">jev<span>omni</span></div><div class="output-line"></div><div class="decision">context → choice</div><div class="art-bottom"><span>SINGLE FORWARD PASS</span><span>↗</span></div></div></article><a class="project-secondary" href="https://github.com/adola700/vee-ana" target="_blank" rel="noopener noreferrer"><span class="project-number">02</span><div><h3>Hinglish text-to-speech</h3><p>Fine-tuning, evaluation, and streaming inference for more natural Hindi–English speech.</p></div><span class="eyebrow project-type">SPEECH</span><span class="big-arrow" aria-hidden="true">↗</span></a></section><section class="section writing"><div class="section-heading"><h2>Writing & notes</h2><a class="quiet-link" href="/blog/">All writing ↗</a></div><p class="section-intro">A notebook for the things I’m building and learning.</p>${rows}</section><section id="about" class="section about"><div><span class="eyebrow">02 / A LITTLE CONTEXT</span><h2>From ideas<br>to working models.</h2></div><div><p>I’m Akhila, a data scientist and IIT Madras graduate working on applied machine learning.</p><p>My projects span multimodal decisions, speech, and reasoning. This is where I share the models, code, and notes along the way.</p><a class="text-link" href="${site.socials.LinkedIn}" target="_blank" rel="noopener noreferrer">More about me on LinkedIn ${arrow}</a></div></section>`;
await writeFile('docs/index.html',layout(site.name+' — Open models & machine learning','Creator of Jev-Omni. Open models, speech experiments, and notes on applied machine learning.','/',home));
await mkdir('docs/blog',{recursive:true});await writeFile('docs/blog/index.html',layout('Writing — '+site.name,'Project notes on multimodal AI, speech, and machine learning.','/blog/',`<section class="blog-header"><span class="eyebrow">THE NOTEBOOK</span><h1>Writing & <em>notes.</em></h1><p class="intro">Models, experiments, and what I learn along the way.</p></section><section class="post-list" aria-label="All posts">${rows}</section>`));
for(const p of posts){const html=`<article class="article"><a class="quiet-link" href="/blog/">← All writing</a><div class="article-meta eyebrow">${esc(p.category)} · ${esc(p.label)} · ${p.readTime} read</div><h1>${esc(p.title)}</h1><p class="article-deck">${esc(p.summary)}</p><div class="byline">${esc(site.name)}<span>Published ${new Date(p.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</span></div><div class="prose">${p.sections.map(s=>(s.heading?`<h2>${esc(s.heading)}</h2>`:'')+`<p>${esc(s.text)}</p>`).join('')}<aside class="source-note"><p>${esc(p.editorialNote)}</p><a href="${esc(p.source)}" target="_blank" rel="noopener noreferrer">${esc(p.sourceLabel)} ${arrow}</a></aside></div></article>`;await mkdir('docs/blog/'+p.slug,{recursive:true});await writeFile('docs/blog/'+p.slug+'/index.html',layout(p.title+' — '+site.name,p.summary,'/blog/'+p.slug+'/',html));}
await writeFile('docs/404.html',layout('Page not found — '+site.name,'This page could not be found.','/404',`<section class="blog-header"><span class="eyebrow">404</span><h1>A little <em>detour.</em></h1><p class="intro">That page isn’t here. Let’s head back.</p><a class="button" href="/">Back home →</a></section>`));
await writeFile('docs/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(site.name)} — Writing</title><link>${site.origin}/blog/</link><description>Project notes and experiments.</description>${posts.map(p=>`<item><title>${esc(p.title)}</title><link>${site.origin}/blog/${p.slug}/</link><guid>${site.origin}/blog/${p.slug}/</guid><pubDate>${new Date(p.date+'T12:00:00Z').toUTCString()}</pubDate><description>${esc(p.summary)}</description></item>`).join('')}</channel></rss>`);
await writeFile('docs/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/blog/',...posts.map(p=>'/blog/'+p.slug+'/')].map(p=>`<url><loc>${site.origin}${p}</loc></url>`).join('')}</urlset>`);
await writeFile('docs/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${site.origin}/sitemap.xml\n`);
console.log(`Built home, blog, ${posts.length} articles, RSS, sitemap, and 404.`);
